spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce-products
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    virtual-host: /
    exchange:
      order: orderExchange
    routing-key:
      order: order.new

server:
  port: 8082

jwt:
  auth:
    converter:
      resource-id: ecommerce-rest-api
      principal-attribute: prefered_username